### ISSUE TITLE
Data Generation Code 

### ISSUE THREAD

**Issue by tgyuan21** [yuchenlin/LLM-Blender#12]
Thanks for the work. Do you plan to release the code that how you generate the MixInstruct Dataset? It would be very helpful!

**Comment by jdf-prog** [comment]
The code is already released:

Code to construct the dataset: [get_mixinstruct.py](https://github.com/yuchenlin/LLM-Blender/blob/main/llm_blender/download_dataset/get_mixinstruct.py)

For candidate generation: refer to [generate_candidates.sh](https://github.com/yuchenlin/LLM-Blender/blob/main/llm_blender/candidates_generation/generate_candidates.sh)

You can also use [LLM-Gen](https://github.com/jdf-prog/LLM-Gen) to do the generation

**Comment by tgyuan21** [comment]
Thanks for the information, I came across CUDA not enough memory issue when generating candidates. 
My setup is 2xT4 15GB, are there any settings that I can tune to reduce the memory consumptions?

**Comment by tgyuan21** [comment]
Thank you for the assistance!
