### ISSUE TITLE
Replicate Experiments

### ISSUE THREAD

**Issue by RaccoonOnion** [yuchenlin/LLM-Blender#13]
Hi congratulations on your work! Do you plan to release the code for replicating your experiments? I only find the pairRanker and Genfuser modules.

**Comment by jdf-prog** [comment]
Please refer to this issue. [https://github.com/yuchenlin/LLM-Blender/issues/8](https://github.com/yuchenlin/LLM-Blender/issues/8)
Hope that will be helpful!
