### ISSUE TITLE
Support for MPS device

### ISSUE THREAD

**Issue by fangyuan-ksgk** [yuchenlin/LLM-Blender#14]
Can you please indicate how I can use your wonderful package in a Mac machine with M2/3 chip? 

Currently I tried:
    blender.loadranker("llm-blender/PairRM", device='mps')
Which works fine, but
    ranks = blender.rank(inputs, candidates_texts, return_scores=False, batch_size=1)
Gives me error as it expects CUDA...

Thanks in advance!

**Comment by jdf-prog** [comment]
This issues has been fixed in the latest github code. Please try reinstall the llm-blender package through 
```bash
pip install git+https://github.com/yuchenlin/LLM-Blender.git
```
