### ISSUE TITLE
Training ranker on Unified-Feedback

### ISSUE THREAD

**Issue by yifei-he** [yuchenlin/LLM-Blender#17]
Hi,

Thank you for the impressive work!

have a question about the training of PairRM. From my understanding, PairRM is trained on Unified-Feedback, which is a dataset suite with pariwise comparison data. On the other hand, from your code (and also the mix-instruct dataset), the training data takes the form of {prompt, candidates, scores}, and the number of candidates is often larger than 2. 

Can you comment on the difference of these two types of training? Also, in the pairwise setting, do you directly treat 'conv_A_rating' and 'conv_B_rating' (mostly either 0 or 1) in Unified-Feedback as scores? Because I find that train_ranker is not directly compatible with Unified-Feedback.

Thanks again!

**Comment by jdf-prog** [comment]
Hi yifei, please refer to this script to change to the mixinstruct format!

https://github.com/jdf-prog/UnifiedFeedback/blob/main/to_mixinstruct_format.py

**Comment by yifei-he** [comment]
Thank you for the pointer!
