### ISSUE TITLE
Split dependencies so that core install is light for model inference

### ISSUE THREAD

**Issue by lewtun** [yuchenlin/LLM-Blender#22]
Hello @yuchenlin 👋 !

We're big fans of PairRM at Hugging Face and would like to feature it in some callbacks we're adding to `trl`. The only drawback is that running

```
pip install git+https://github.com/yuchenlin/LLM-Blender.git
```

installs many dependencies besides those need for model inference (e.g. `spacy`, `openai` etc). Would it be possible to split your `setup.py` so that the core deps are just those for inference / running the model, and the remainder are optional?

To give you an idea of what I mean, here's how we handle this in our alignment handbook: https://github.com/huggingface/alignment-handbook/blob/main/setup.py

Thanks!

**Comment by jdf-prog** [comment]
Sure, Thanks for the suggestion! I will take a look at your practice about how write setup.py and then change the file asap. Appreciate your love for PairRM, btw!

**Comment by jdf-prog** [comment]
Hey @lewtun , I have updated the `setup.py` and now it only requires the neccessary packages for infernece. Please check it out [setup.py(https://github.com/yuchenlin/LLM-Blender/blob/main/setup.py)

**Comment by lewtun** [comment]
Thanks a lot @jdf-prog ! Unfortunately, I am now getting an error from the `hf_space` submodule:

```
Collecting git+https://github.com/yuchenlin/LLM-Blender.git
  Cloning https://github.com/yuchenlin/LLM-Blender.git to /tmp/pip-req-build-2s310mse
  Running command git clone --filter=blob:none --quiet https://github.com/yuchenlin/LLM-Blender.git /tmp/pip-req-build-2s310mse
  Resolved https://github.com/yuchenlin/LLM-Blender.git to commit 3f22a1bead900a78f9aaa598ff1819f685443f7b
  Running command git submodule update --init --recursive -q
  fatal: remote error: upload-pack: not our ref b8f3dabc4eeccea67c5bc179e04cac3b2617204b
  fatal: the remote end hung up unexpectedly
  fatal: Fetched in submodule path 'hf_space/LLM-Blender', but it did not contain b8f3dabc4eeccea67c5bc179e04cac3b2617204b. Direct fetching of that commit failed.
  error: subprocess-exited-with-error
  
  × git submodule update --init --recursive -q did not run successfully.
  │ exit code: 128
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× git submodule update --init --recursive -q did not run successfully.
│ exit code: 128
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

Repro in this Colab: https://colab.research.google.com/drive/1wOionJ4WjZ4K4Sa04yiga9RI_aWaXbzQ?usp=sharing

**Comment by jdf-prog** [comment]
@lewtun Thanks for pointing out! It's a submodule error. It now has been fixed and should be good to use! Please try install again!

**Comment by jdf-prog** [comment]
@lewtun Did you try the installation again? I have tried on my side and it seems to work well. Please let me know if you encounter any problem.

**Comment by lewtun** [comment]
It works great, thanks!
