### ISSUE TITLE
Make `llm-blender` available on PyPI

### ISSUE THREAD

**Issue by lewtun** [yuchenlin/LLM-Blender#23]
Hello @jdf-prog now that #22 is resolved, I'd like to make one final request to see whether `llm_blender` could be made available on PyPI so that one can run:

```
pip install llm_blender
```

This would allow us to include `llm_blender` as an optional dependency in TRL instead of asking the user to run the `pip install git+{}` command. 

Thank you!

**Comment by jdf-prog** [comment]
Hi @lewtun You can now install with `pip install llm-blender`. Thanks for the suggestion!

**Comment by lewtun** [comment]
Amazing, thank you so much!
