### ISSUE TITLE
How to use gen_fuser alone for merging?

### ISSUE THREAD

**Issue by 20191864218** [yuchenlin/LLM-Blender#25]
Thank you for your excellent work. I have a question for you. If I want to use gen_fuser to merge two reports and output the final report, how should I do it?

Report 1: You are very cute, with big eyes and a beautiful face.
Report 2: You are very beautiful, with long hair and big eyes.

Thank you for your response.

**Comment by jdf-prog** [comment]
Please check [https://github.com/yuchenlin/LLM-Blender/blob/main/blender_usage.ipynb](https://github.com/yuchenlin/LLM-Blender/blob/main/blender_usage.ipynb) usecase 3 for the codes. Simply replace your input and candidate texts with your input command and the two reports, then it will be good.
