### ISSUE TITLE
How to blend generations from different LLMs?

### ISSUE THREAD

**Issue by Sunt-ing** [yuchenlin/LLM-Blender#26]
I'm interested in trying blending generations from different LLMs, but it seems that currently we can only blend different generations from the same model using `best_of_n`.

**Comment by jdf-prog** [comment]
You can get any response candidate for the query from any models, then pass them into the function as `candidates` arg to do either ranking fusing for the output blending. It's not limited to outputs from the same model.

**Comment by Sunt-ing** [comment]
Thanks!
