### ISSUE TITLE
Can I load modules and checkpoints from local files？

### ISSUE THREAD

**Issue by wangq326** [yuchenlin/LLM-Blender#27]
Hello, your work is exceptional, and I am very interested in it. However, I am unable to load models from Hugging Face. Is it possible for me to download the checkpoints you have released and load them from local files?

Looking forward to your reply. Best regards!

**Comment by jdf-prog** [comment]
Can you post what errors you have encountered during the loading?

**Comment by jdf-prog** [comment]
```python
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
import llm_blender
blender = llm_blender.Blender()
# Load Ranker
blender.loadranker("llm-blender/PairRM") # load ranker checkpoint
```
For me, the above code, and the codes in the readme works fine for me. It will be good if you can provide more error information so I can help you solve it.

**Comment by jdf-prog** [comment]
About the local files, of course it's possible. simply replace the model_name to your local checkpoint path.
