### ISSUE TITLE
Fine-tuning PairRM error

### ISSUE THREAD

**Issue by newborn1** [yuchenlin/LLM-Blender#28]
Very excellent research. I would like to try full fine-tuning on your trained optimal model, but I can't find a trainable model that I can use for loading. When I try to load the model on huggingface and fine tune the training on train_ranker.py I find that the parameters are not compatible with “TypeError: Could not infer framework from class <class 'llm_blender.blender.blender.Blender'>.”
Could you please provide me with the “checkpoint-best” that can be loaded and fine-tuned in train_ranker.py and how to use it? Thank you very much!

**Comment by jdf-prog** [comment]
The training do not need the `checkpoint-best` to start, that's the output directory name. Could you please provide more details on the training errors, such as the environments and error message, error code line? Did you install your environment correctly via `pip install -e .[train,eval]`.  On my side, all the training works fine.
