### ISSUE TITLE
Question about the fuser outputs

### ISSUE THREAD

**Issue by sai4july** [yuchenlin/LLM-Blender#5]
I am confused that all my outputs from the `fuser' are nonsense. For example, they all look like '-  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  - '. I am wondering whether this is due to my task being a classification task. Maybe the method is more suitable for traditional generation tasks.

**Comment by yuchenlin** [comment]
It's true that we only trained it on open-ended generation tasks (instruction-following examples particularly), as shown in our paper and data. What are the particular inputs that you are using?

**Comment by sai4july** [comment]
Classification type samples from the CBLUE dataset, which is a medical dataset.

**Comment by yuchenlin** [comment]
ic, then I'd suggest you follow the steps to generate the candidates from LLMs on relevant domain-specific data and then fine-tune your own specific fusion model, such that the training distribution will be closer to your test cases.

**Comment by sai4july** [comment]
Good suggestion, thx.
