### ISSUE TITLE
Issues with the split of dataset

### ISSUE THREAD

**Issue by Cascol-SCUT** [yuchenlin/LLM-Blender#7]
## There is maybe domain shift in the current split of training, validating and testing dataset by measuring the best rate of  each model.
I select bartscore as the measurement, and analysis the best rate of each model in the dataset
- where _best rate = sum(is_best)/len(dataset)_.

It can be seen that there is a huge different in the following statics. For example OA, which achieves 14.47% on train, 21.38% on test, but 0.88% on validation:

![image](https://github.com/yuchenlin/LLM-Blender/assets/51443787/b6ee93a3-d6c6-4556-bc03-05c71b3faa4c)
![image](https://github.com/yuchenlin/LLM-Blender/assets/51443787/9a30ac03-50a3-4d89-9537-23d50fd5d0b2)
![image](https://github.com/yuchenlin/LLM-Blender/assets/51443787/18f17f84-fbc6-4bfc-a9d1-06960110f063)

**Comment by jdf-prog** [comment]
Could you provide your evaluation scipt?
My following script that counting the best model percentage **do not report this domain shift at all**.
```python
from collections import defaultdict
import datasets
mixinstruct = datasets.load_dataset("llm-blender/mix-instruct")
using_metric = 'bartscore'
for split in ['train', 'validation', 'test']:
    best_model_count = defaultdict(int)
    for item in mixinstruct[split]:
        cand_metric_scores = [cand['scores'][using_metric] for cand in item['candidates']]
        best_cand_idx = cand_metric_scores.index(max(cand_metric_scores))
        best_model = item['candidates'][best_cand_idx]['model']
        best_model_count[best_model] += 1
    print("Percentage of best model in {} for split {}:".format(using_metric, split))
    sorted_best_model_count = sorted(best_model_count.items(), key=lambda x: x[1], reverse=True)
    sorted_best_model_count = {k: v for k, v in sorted_best_model_count}
    for model, count in sorted_best_model_count.items():
        print("  {}: {:.2f}%".format(model, count / len(mixinstruct[split]) * 100))
```
The output best model percentages for train/val/test are
```txt
Percentage of best model in bartscore for split train:
  moss-moon-003-sft: 21.90%
  vicuna-13b-1.1: 18.81%
  oasst-sft-4-pythia-12b-epoch-3.5: 14.47%
  alpaca-native: 10.06%
  llama-7b-hf-baize-lora-bf16: 8.95%
  chatglm-6b: 8.44%
  koala-7B-HF: 4.56%
  mpt-7b-instruct: 4.35%
  dolly-v2-12b: 3.23%
  stablelm-tuned-alpha-7b: 2.74%
  mpt-7b: 1.60%
  flan-t5-xxl: 0.89%
Percentage of best model in bartscore for split validation:
  vicuna-13b-1.1: 20.40%
  oasst-sft-4-pythia-12b-epoch-3.5: 16.10%
  alpaca-native: 12.00%
  llama-7b-hf-baize-lora-bf16: 10.76%
  moss-moon-003-sft: 10.64%
  chatglm-6b: 10.36%
  koala-7B-HF: 5.00%
  mpt-7b-instruct: 4.62%
  dolly-v2-12b: 4.06%
  stablelm-tuned-alpha-7b: 3.00%
  mpt-7b: 2.18%
  flan-t5-xxl: 0.88%
Percentage of best model in bartscore for split test:
  vicuna-13b-1.1: 21.38%
  oasst-sft-4-pythia-12b-epoch-3.5: 16.50%
  chatglm-6b: 11.54%
  moss-moon-003-sft: 11.18%
  alpaca-native: 10.56%
  llama-7b-hf-baize-lora-bf16: 9.44%
  koala-7B-HF: 5.14%
  mpt-7b-instruct: 4.34%
  dolly-v2-12b: 3.60%
  stablelm-tuned-alpha-7b: 3.30%
  mpt-7b: 2.08%
  flan-t5-xxl: 0.94%
```

**Comment by jdf-prog** [comment]
The whole process of constructing the mixinstruct dataset is also integrated in a single python script here. And the train/val/test is simply shuffled first and then splitted. This kind of domain shift should not exist **due to the simple shuffling operation**

**Comment by Cascol-SCUT** [comment]
I mistakely thinks every model correspond to the same index in every sample. Will close this issue.
