### ISSUE TITLE
Unable to reproduce the results in the paper

### ISSUE THREAD

**Issue by wang-debug** [yuchenlin/LLM-Blender#8]
May I kindly inquire about the methodology used to obtain the final results presented in Table 2 of your paper? I have attempted to replicate the results without success. Below, I am providing the inference code I used for your reference. I am eagerly looking forward to your response. Thank you for your assistance. :)

```
batch_size = 16
metrics = ['bleurt']

import llm_blender
import numpy as np
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "1"
import copy
from llm_blender.common.evaluation import overall_eval
import datasets
import json

mixinstruct_test = datasets.load_dataset("llm-blender/mix-instruct", split="test", streaming=True)
mixinstruct_test = list(mixinstruct_test)
# remove cmp_results with none cmp results
for ex in mixinstruct_test:
    ex['cmp_results'] = json.loads(ex['cmp_results'])
mixinstruct_test = [x for x in mixinstruct_test if x['cmp_results']]
inputs = [x['input'] for x in mixinstruct_test]
candidates_texts = [[cand['text'] for cand in x['candidates']] for x in mixinstruct_test]
targets = [x['output'] for x in mixinstruct_test]



ranker_config = llm_blender.RankerConfig
ranker_config.ranker_type = "pairranker"
ranker_config.model_type = "deberta"
ranker_config.model_name = "microsoft/deberta-v3-large"
ranker_config.load_checkpoint = "./hf_models/pairranker-deberta-v3-large"
ranker_config.cache_dir = "./hf_models"
ranker_config.source_max_length = 128
ranker_config.candidate_max_length = 128
ranker_config.n_tasks = 1
fuser_config = llm_blender.GenFuserConfig
fuser_config.model_name = "llm-blender/gen_fuser_3b"
fuser_config.cache_dir = "./hf_models"
fuser_config.max_length = 512
fuser_config.candidate_max_length = 128
blender_config = llm_blender.BlenderConfig
blender_config.device = "cuda"
blender = llm_blender.Blender(blender_config, ranker_config, fuser_config)
results = {}
fuse_generations, ranks = blender.rank_and_fuse(inputs, candidates_texts, return_scores=False, batch_size=batch_size, top_k=3)

print("start evaluation...")

scores = overall_eval(fuse_generations, targets, metrics)
print(f"Fusion Scores")
for key, value in scores.items():
    print("  ", key+":", np.mean(value))

print("LLM Scores")
llms = [x['model'] for x in mixinstruct_test[0]['candidates']]
llm_scores_map = {llm: {metric: [] for metric in metrics} for llm in llms}

for ex in mixinstruct_test:
    for cand in ex['candidates']:
        for metric in metrics:
            llm_scores_map[cand['model']][metric].append(cand['scores'][metric])
for i, (llm, scores_map) in enumerate(llm_scores_map.items()):
    print(f"{i} {llm}")
    for metric, llm_scores in llm_scores_map[llm].items():
        print("  ", metric+":", "{:.4f}".format(np.mean(llm_scores)))
```

**Comment by jdf-prog** [comment]
Thank you for your question. I will check it and response you asap.

**Comment by jdf-prog** [comment]
I notice that the fuesr max_length is set to 512. However, in our evaluation setting, the fuser max_length is set to 1024 instead. Could you try the inference code again with fuser max length being 1024?
In the jupyter example, the fuser max length is set to 512 for example usage only. Sorry about the confusion.

**Comment by wang-debug** [comment]
Ok, I'll try that first; also I noticed that there are 12 outputs per instruction in `mixinstruct`, which is different from the 11 recounted in the article, is it possible that one of the answers generated by `mpt-7b` is not among them?

**Comment by jdf-prog** [comment]
Yeah. `mpt-7b` is kept in the mixinstruct for history reason. In the experiments. In the experiments mpt-7b's results is included, but simply ignored. And I think `mpt-7b` produce quite similar resuls with `mpt-instruct`, therefore, the difference caused by removing `mpt-7b` or not will not be that clear.

**Comment by wang-debug** [comment]
It seems that this attempt has still failed. 
Currently, the differences in my code compared to the one mentioned above lie in the max length of the fuser and the filtering out of `mpt-7b` outputs from each output set. 

Below are the results I obtained:
` bartscore: -2.488526064928311
   bertscore: 0.7782205578491789
   bleurt: -0.2401316081634597`

When you were evaluating, did you use 5k or 4,771 examples?

**Comment by jdf-prog** [comment]
I use the 5k for the auto-metrics. I will also conduct some experiments here to see the problem. Will notice you soon.

**Comment by jdf-prog** [comment]
@wang-debug I believe there is a small bug in your evaluation code: You forgot to include the instructions in the blender function.
Also, you should try all the 5k exmaples.
Please extract the instructions with `insts = [x['instruction'] for x in mixinstruct_test]` 
and add the insts to the `rank_and_fuse` function by 
`fuse_generations, ranks = blender.rank_and_fuse(inputs, candidates_texts, instructions=insts, return_scores=False, batch_size=batch_size, top_k=3)
`
Then you should be able to reproduce the results in table 2.

**Comment by jdf-prog** [comment]
Btw, it's helpful if you can close this issue if you reproduce the paper results successfully and don't have further questions.

**Comment by wang-debug** [comment]
Thank you for your assistance!
