### ISSUE TITLE
name 'vllm' is not defined

### ISSUE THREAD

**Issue by siddiquelatif** [yuchenlin/LLM-Blender#9]
Trying to run the inference notebook. Getting the following error:

<img width="1134" alt="Screenshot 2023-12-01 at 1 30 22 pm" src="https://github.com/yuchenlin/LLM-Blender/assets/34917150/0cd73f95-debb-4ebd-ad77-e829595f451b">

**Comment by jdf-prog** [comment]
Can you try delete the variable type comments  `Union[transformers.PreTrainedModel, vllm.LLM]`? Will there still be errors?

**Comment by jdf-prog** [comment]
Hi @siddiquelatif , I have tested this bug, and removed this comment in the latest version, 
before
```python
def best_of_n_generate(
        self,
        model: Union[transformers.PreTrainedModel, vllm.LLM], # Union[transformers.PreTrainedModel, vllm.LLM]
        model_tokenizer:transformers.PreTrainedTokenizer,
...
```
after
```python
def best_of_n_generate(
        self,
        model, # Union[transformers.PreTrainedModel, vllm.LLM]
        model_tokenizer:transformers.PreTrainedTokenizer,
...
```
so there will be bugs if vllm is not installed. However, VLLM models are also supported if you want. Please try to reinstall the LLM-blender package. This bug will be fixed.

**Comment by siddiquelatif** [comment]
Thanks @Dongfu Jiang,

Yes, its working. Thanks again. :)
